---
- name: Web Server Set-Up
  hosts: webServers
  become: yes
  tasks:
    - name: Installing httpd  
      yum: 
        name: httpd
        state: present
    - name: Starting Apache or Httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Deploying Website
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html

- name: Database Server Set-Up
  hosts: db
  become: yes 
  tasks:
    - name: Update apt-get repo and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Installing Maria DB
      apt:
        name: mariadb-server
        state: present 

    - name: Starting Maria DB
      service:
        name: mariadb
        enabled: true
        state: started 
   
