---
- name: Web Server Set-Up
  hosts: webServers
  become: yes
  tasks:
    - name: Installing Apache2
      apt:
        name: apache2
        state: present

    - name: Starting Apache
      service:
        name: apache2
        enabled: true
        state: started

    - name: Deploying Website
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html

- name: Database Server Set-Up
  hosts: db
  become: yes 
  tasks:
    - name: Installing Maria DB
      apt:
        name: mariadb-server
        state: present 
    - name: Starting Maria DB
      service:
        name: mariadb
        enabled: true
        state: started 
   
